language: emacs-lisp
before_script:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs24 emacs24-el emacs24-common-non-dfsg
  - curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
script:
  - PATH="/home/travis/.cask/bin:$PATH" make
